// const { fontFamily } = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  // darkMode: 'class',
  darkMode: ['class'],
  theme: {
    // colors: {
    //   'gpt-dark-gray': '#171717',
    // },
    fontFamily: {
      sans: ['Inter', 'sans-serif'],
      mono: ['Roboto Mono', 'monospace'],
    },
    // fontFamily: {
    //   sans: ['Söhne', 'sans-serif'],
    //   mono: ['Söhne Mono', 'monospace'],
    // },
    extend: {
      width: {
        'authPageWidth': '370px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      colors: {
        white: '#FDFBFB',
        black: '#1A1A1A',
        gray: {
          20: '#FDFBFB',
          50: '#f0f0f0',
          100: '#EEEEEE',
          200: '#d6d6d6',
          300: '#bebebe',
          400: '#999999',
          500: '#707070',
          600: '#474747',
          700: '#333333',
          800: '#2e2e2e',
          850: '#242424',
          900: '#1A1A1A',
        },
        pink: {
          20: '#FDFBFB',
          50: '#fff6f5',
          100: '#ffe3e0',
          200: '#ffd1cc',
          300: '#ffbfb8',
          400: '#ffb5ad',
          500: '#ffaca3',
          600: '#ffa399',
          700: '#e6938a',
          800: '#b3726b',
          850: '#80524d',
          900: '#4c312e',
        },
        // green: {
        //   20: '#FDFBFB',
        //   50: '#fff6f5',
        //   100: '#ffe3e0',
        //   200: '#ffd1cc',
        //   300: '#ffbfb8',
        //   400: '#ffb5ad',
        //   500: '#ffaca3',
        //   600: '#ffa399',
        //   700: '#e6938a',
        //   800: '#b3726b',
        //   850: '#80524d',
        //   900: '#4c312e',
        // },
        blue: {
          20: '#FDFBFB',
          50: '#f1faf9',
          100: '#e3f4f3',
          200: '#d6efec',
          300: '#bae5e0',
          400: '#9edad4',
          500: '#83cfc7',
          600: '#75cac1',
          700: '#69b6ae',
          800: '#528d87',
          850: '#3b6561',
          900: '#172827',
        },
        'brand-purple': '#ffa399',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-secondary-alt': 'var(--text-secondary-alt)',
        'text-tertiary': 'var(--text-tertiary)',
        'surface-primary': 'var(--surface-primary)',
        'surface-primary-alt': 'var(--surface-primary-alt)',
        'surface-primary-contrast': 'var(--surface-primary-contrast)',
        'surface-secondary': 'var(--surface-secondary)',
        'surface-tertiary': 'var(--surface-tertiary)',
        'surface-tertiary-alt': 'var(--surface-tertiary-alt)',
        'border-light': 'var(--border-light)',
        'border-medium': 'var(--border-medium)',
        'border-medium-alt': 'var(--border-medium-alt)',
        'border-heavy': 'var(--border-heavy)',
        'border-xheavy': 'var(--border-xheavy)',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('tailwindcss-radix')(),
    // require('@tailwindcss/typography'),
  ],
};
